# Generated by Django 5.2.4 on 2025-07-22 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevilFruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "Paramecia"), ("Z", "Zoan"), ("L", "Logia")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "devil_fruit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("observation_haki", models.BooleanField(default=False)),
                ("armament_haki", models.BooleanField(default=False)),
                ("conqueror_haki", models.BooleanField(default=False)),
                ("img_url", models.URLField(blank=True, null=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Admiral", "Almirante"),
                            ("Vice Admiral", "Vice-Almirante"),
                            ("Rear Admiral", "Contra-Almirante"),
                            ("Captain", "Capitão"),
                            ("Lieutenant", "Tenente"),
                            ("Marine", "Soldado"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pirate",
            name="armament_haki",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pirate",
            name="conqueror_haki",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pirate",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pirate",
            name="observation_haki",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ship", models.CharField(blank=True, max_length=100, null=True)),
                ("img_url", models.URLField(blank=True, null=True)),
                (
                    "captain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_captain",
                        to="api.pirate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pirate",
            name="crew",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pirates",
                to="api.crew",
            ),
        ),
    ]
