# Generated by Django 5.2.4 on 2025-07-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_devilfruit_marine_pirate_armament_haki_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marine",
            name="devil_fruit",
        ),
        migrations.RemoveField(
            model_name="pirate",
            name="devil_fruit",
        ),
        migrations.AddField(
            model_name="marine",
            name="devilfruit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.devilfruit",
            ),
        ),
        migrations.AddField(
            model_name="marine",
            name="portrait_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pirate",
            name="devilfruit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.devilfruit",
            ),
        ),
        migrations.AddField(
            model_name="pirate",
            name="portrait_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
