# Generated by Django 5.2.4 on 2025-07-25 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_marine_devil_fruit_remove_pirate_devil_fruit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marine",
            name="devilfruit",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.devilfruit",
            ),
        ),
        migrations.AlterField(
            model_name="pirate",
            name="devilfruit",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.devilfruit",
            ),
        ),
    ]
