# Generated by Django 5.2.4 on 2025-07-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_marine_devilfruit_alter_pirate_devilfruit"),
    ]

    operations = [
        migrations.AddField(
            model_name="marine",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marine",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pirate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pirate",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
