# Generated by Django 5.2.4 on 2025-08-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_marine_description_marine_history_pirate_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="character_images/")),
                ("type", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        choices=[
                            ("portrait", "Portrait"),
                            ("character", "Character"),
                            ("fruit", "Fruit"),
                            ("crew", "Crew"),
                        ],
                    ),
                ),
            ],
        ),
    ]
