# Generated by Django 5.2.4 on 2025-08-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pirate",
            name="bounty",
            field=models.PositiveBigIntegerField(),
        ),
    ]
