version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_django
    restart: always
    environment:
      POSTGRES_DB: mugiwaradex-db
      POSTGRES_USER: natanael
     POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
